### PR TITLE
Update play and fix files resolution in prod mode

### PR DESCRIPTION
**Pull request by zikolach**
- updated play
- resolve files from classpath (fixed file not found in prod)

### CODE REVIEW

**Comment by ssorallen** [comment]
Can you remove all of the extra spaces added in the pull request? Then I'll test this out and get it merged.

**Comment by ssorallen** [comment]
Thanks for this by the way! Looking forward to getting this up-to-date.

**Comment by zikolach** [comment]
Added .editorconfig with formatting settings compatible with old formatting. Let me know if something else needs to be updated.

**Comment by rjerue** [comment]
What's the status on this?

**Comment by zikolach** [comment]
Waiting to be merged for 4 months now :)

**Comment by rjerue** [comment]
It works for the latest 2.5.10.

The only thing I'm trying to figure out is how to add other dependencies for Nashorn to render (particularly react-chartjs).

**Pull request merged**
